# Project:   dfe-transform-vrl
# File:      clippy.toml
# Purpose:   Clippy linter configuration
# Language:  TOML
#
# License:   BUSL-1.1
# Copyright: (c) 2026 HYPERI PTY LIMITED

too-many-arguments-threshold = 7
cognitive-complexity-threshold = 25
type-complexity-threshold = 350
too-many-lines-threshold = 150
