# Project:   dfe-transform-vrl
# File:      Dockerfile
# Purpose:   production container image
#
# License:   BUSL-1.1
# Copyright: (c) 2026 HYPERI PTY LIMITED
#
# AUTOGENERATED -- do not edit by hand.
# Generated by scalo::deployment::generate_dockerfile()
# Schema version: 3
# Source contract: dfe-transform-vrl::deployment::contract()
# Regenerate with: `dfe-transform-vrl emit-dockerfile > Dockerfile`

FROM debian:trixie-slim

LABEL io.hyperi.profile="production"

# Runtime shared libraries for dynamically-linked Rust crates.
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl netcat-openbsd iputils-ping gnupg \
    && curl -fsSL https://packages.confluent.io/clients/deb/archive.key -o /tmp/repo-key.asc \
    && gpg --show-keys --with-colons --with-fingerprint /tmp/repo-key.asc \
       > /tmp/repo-key.info \
    && grep -q "^fpr:::::::::CBBB821E8FAF364F79835C438B1DA6120C2BF624:" /tmp/repo-key.info \
    && rm -f /tmp/repo-key.info \
    && gpg --dearmor -o /usr/share/keyrings/confluent-clients.gpg /tmp/repo-key.asc \
    && rm -f /tmp/repo-key.asc \
    && echo "deb [signed-by=/usr/share/keyrings/confluent-clients.gpg] \
       https://packages.confluent.io/clients/deb bookworm main" \
       > /etc/apt/sources.list.d/confluent-clients.list \
    && apt-get update && apt-get install -y --no-install-recommends \
       librdkafka1 libssl3t64 zlib1g \
    && rm -rf /var/lib/apt/lists/*

COPY dfe-transform-vrl /usr/local/bin/dfe-transform-vrl
RUN chmod +x /usr/local/bin/dfe-transform-vrl

# Ubuntu 24.04 ships with ubuntu user at UID 1000 -- remove before creating appuser
RUN if id ubuntu >/dev/null 2>&1; then userdel -r ubuntu; fi && useradd --create-home --uid 1000 appuser
USER appuser

EXPOSE 9090 9000

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD curl -sf http://localhost:9090/livez > /dev/null || exit 1

ENTRYPOINT ["dfe-transform-vrl"]
CMD ["--config", "/etc/dfe-transform-vrl/config.yaml"]

