apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dfe-transform-vrl.fullname" . }}-config
  labels:
    {{- include "dfe-transform-vrl.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
