{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "dfe-transform-vrl.fullname" . }}
  labels:
    {{- include "dfe-transform-vrl.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "dfe-transform-vrl.fullname" . }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  triggers:
    - type: kafka
      authenticationRef:
        name: {{ include "dfe-transform-vrl.fullname" . }}-kafka-auth
      metadata:
        bootstrapServers: {{ join "," .Values.config.source.brokers | quote }}
        consumerGroup: {{ .Values.keda.kafka.consumerGroup | default .Values.config.source.group_id | quote }}
        topic: {{ .Values.keda.kafka.topic | default (index .Values.config.source.topics 0) | quote }}
        lagThreshold: {{ .Values.keda.kafka.lagThreshold | quote }}
        activationLagThreshold: {{ .Values.keda.kafka.activationLagThreshold | quote }}
        saslType: scram_sha512
        tls: {{ if .Values.config.source.tls.enabled }}enable{{ else }}disable{{ end }}
    {{- if .Values.keda.cpu.enabled }}
    - type: cpu
      metricType: Utilization
      metadata:
        value: {{ .Values.keda.cpu.threshold | quote }}
    {{- end }}
{{- end }}
