{{- if and .Values.keda.enabled .Values.keda.cpu.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "dfe-transform-vrl.fullname" . }}
  labels:
    {{- include "dfe-transform-vrl.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "dfe-transform-vrl.fullname" . }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  triggers:
    {{- if .Values.keda.cpu.enabled }}
    # CPU utilisation (only scaler)
    - type: cpu
      metricType: Utilization
      metadata:
        value: {{ .Values.keda.cpu.threshold | quote }}
    {{- end }}
{{- end }}
