{{- if not .Values.kafka.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dfe-transform-vrl.kafkaSecretName" . }}
  labels:
    {{- include "dfe-transform-vrl.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.kafka.secretKeys.username }}: {{ .Values.kafka.username | b64enc | quote }}
  {{ .Values.kafka.secretKeys.password }}: {{ .Values.kafka.password | b64enc | quote }}
{{- end }}
