apiVersion: v1
kind: Service
metadata:
  name: {{ include "dfe-transform-vrl.fullname" . }}
  labels:
    {{- include "dfe-transform-vrl.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: health
  selector:
    {{- include "dfe-transform-vrl.selectorLabels" . | nindent 4 }}
